route:
  receiver: 'telegram-prod-reciever' #слать по умолчанию
  group_by: ['alertname', 'instance'] #подавление дублей
  group_wait: 10s #Alertmanager подождёт 10 секунд, чтобы собрать похожие алерты перед отправкой первой нотификации 
  group_interval: 10s #после отправки первой группы похожих алертов он будет ждать X перед отправкой следующей группы уведомлений по тем же алерта
  repeat_interval: 5m #повторения отправки в случае неустранения
  routes:
    - match_re:
        environment: 'dev|stage'
      receiver: 'telegram-dev-stage-reciever'
    - match:
        environment: 'prod'
      receiver: 'telegram-prod-reciever'

receivers:
  - name: 'telegram-dev-stage-reciever' #dev
    telegram_configs:
      - bot_token: '7689095579:AAHqwo7Eb-uMNVPF8mC5YIR4l1a8AyOci7Q'
        chat_id: -1002814198121
        message: |
          
          {{ if eq .Status "firing" }}
          🚨 Alert: {{ .CommonLabels.alertname }} |
          🔥 Target: {{ .CommonLabels.instance }}
          Severity: {{ .CommonLabels.severity }} |
          {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
          {{ else }}
          ✅ Resolved: {{ .GroupLabels.alertname }} |
          🔥 Target: {{ .CommonLabels.instance }}
          Severity: {{ .CommonLabels.severity }} |
          {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
          {{ end }}
          
  - name: 'telegram-prod-reciever' #prod
    telegram_configs:
      - bot_token: '8192803973:AAG69jUshiKB6GLupoqKho0l-nFvYs-nXxA'
        chat_id: -1002592193786
        message: |
          
          {{ if eq .Status "firing" }}
          🚨 Alert: {{ .CommonLabels.alertname }} |
          🔥 Target: {{ .CommonLabels.instance }}
          Severity: {{ .CommonLabels.severity }} |
          {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
          {{ else }}
          ✅ Resolved: {{ .GroupLabels.alertname }} |
          🔥 Target: {{ .CommonLabels.instance }}
          Severity: {{ .CommonLabels.severity }} |
          {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
          {{ end }}
          
